### ISSUE TITLE
Legion Prep Quick Testing

### ISSUE THREAD

**Issue by ShaunaGordon** [fizzwidget/digger-aid#1]
I don't know if you have work on this that you just haven't uploaded or if you just haven't gotten to it, but I noticed this one didn't get Legion updates yet, so I figured I'd toss it in and see how badly it broke.

The good news is, it doesn't throw errors on load. The bad news is that, upon testing, it's outputting the wrong faction. 

I'm currently in the Vale of Eternal Blossoms, at a Pandaren digsite, and it keeps outputting Troll updates. Additionally, it's not solving the current Pandaren digsite:

![digsite](https://cloud.githubusercontent.com/assets/579361/17797250/7ac22290-6595-11e6-868f-e608b9e02ce7.png)

I verified this issue by going to a Nightelf digsite...and DiggerAid thought it was an Ogre site.

It's currently getting late here on the East Coast, so I can't dig into this right now, but figured I'd post my findings. If you get to it, or have already gotten to it, cool. If not, I'll take a look at it tomorrow morning and see if I can't get it working properly again.

**Comment by fizzwidget** [comment]
> I'm currently in the Vale of Eternal Blossoms, at a Pandaren digsite, and it keeps outputting Troll updates. 

I used to have a troll intern to take care of all my auction house business, but I fired him after he ran off to "do mojo" too many times. Maybe he be getting' his revenge now, mon?

The API for archaeology stuff is horribly order-dependent... and they like to reorder things on every expansion now. Fixed and tagged a 7.0 release.
