### ISSUE TITLE
addons

### ISSUE THREAD

**Issue by theonlycanadianmoose** [fizzwidget/digger-aid#2]
Neither DiggerAid 7.0, nor FactionFriend 7.0 are loading for me in game.

**Comment by fizzwidget** [comment]
The zip files have the wrong implicit folder name, so the addons don't come out as `GFW_DiggerAid`, `GFW_FactionFriend`, etc the way they're supposed to, which prevents them from loading. (That'll teach me to let Github make my zip files.) 

I can't easily fix the zip files already here (I'll look into it), but if you re-download from www.wowinterface.com or www.fizwidget.com you'll get the right stuff now.
